import Navbar from "@/components/Navbar";
import "./globals.css";
import { Albert_Sans } from "next/font/google";

const inter = Albert_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
